package com.example.githubappstore.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette (Material Theme Builder, Tonal Spot)
internal val md_theme_light_primary = Color(0xFF4F49A8)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFE3DFFF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF140D4A)
internal val md_theme_light_secondary = Color(0xFF5C5B72)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFE2DFF0)
internal val md_theme_light_onSecondaryContainer = Color(0xFF1A192B)
internal val md_theme_light_background = Color(0xFFFDFBFF)
internal val md_theme_light_onBackground = Color(0xFF1C1B1F)
internal val md_theme_light_surface = Color(0xFFFDFBFF)
internal val md_theme_light_onSurface = Color(0xFF1C1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE6E0F0)
internal val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
internal val md_theme_light_error = Color(0xFFB3261E)

// Dark palette
internal val md_theme_dark_primary = Color(0xFFC7C2FF)
internal val md_theme_dark_onPrimary = Color(0xFF271F66)
internal val md_theme_dark_primaryContainer = Color(0xFF3A3390)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFE3DFFF)
internal val md_theme_dark_secondary = Color(0xFFC6C3DB)
internal val md_theme_dark_onSecondary = Color(0xFF302F42)
internal val md_theme_dark_secondaryContainer = Color(0xFF464559)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFE2DFF0)
internal val md_theme_dark_background = Color(0xFF1C1B1F)
internal val md_theme_dark_onBackground = Color(0xFFE6E1E6)
internal val md_theme_dark_surface = Color(0xFF1C1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE6E1E6)
internal val md_theme_dark_surfaceVariant = Color(0xFF49454E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
internal val md_theme_dark_error = Color(0xFFF2B8B5)
